### ISSUE TITLE
Label set data

### ISSUE THREAD

**Issue by sathibault** [nrc-cnrc/NRC-GAMMA#1]
I think it would be useful to provide the label sets associated with the cropped images.  This data would allow one to estimate higher resolution dial position based on the cases where adjacent labels were present or to filter out ambiguous cases.

**Comment by PatrickPaul-NRC** [comment]
Thank you for opening this issue. I think that perhaps I don't understand exactly your comment. At the root of the dataset's tar file there is the Metadata.csv file which has the label for each of the cropped images. If you look at the format of that file you will notice that each row is for one of the two dials at a given time. There are some entries with 2 labels for the same timestamp/dial when the manual annotation was still ambiguous.

**Comment by sathibault** [comment]
Okay, that is good to know.  I did not find documentation on the Metadata.csv format and it didn't notice there were multiple rows for some dials.

My original question was about the raw data that you collected which consisted of a set of labels for each dial from a set of annotators.  However, I think the your answer above is sufficient for use case.
